# Generated by Django 3.0.8 on 2020-07-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
